export const yarnWeights = [
  {
    crochet_gauge: null,
    id: 9,
    knit_gauge: null,
    name: 'Thread',
    ply: null,
    wpi: null,
    yarnstandard: '0: Lace',
  },
  {
    crochet_gauge: null,
    id: 8,
    knit_gauge: null,
    name: 'Cobweb',
    ply: '1',
    wpi: null,
    yarnstandard: '0: Lace',
  },
  {
    crochet_gauge: '',
    id: 7,
    knit_gauge: '32-34',
    name: 'Lace',
    ply: '2',
    wpi: null,
    yarnstandard: '0: Lace',
  },
  {
    crochet_gauge: null,
    id: 13,
    knit_gauge: '32',
    name: 'Light Fingering',
    ply: '3',
    wpi: null,
    yarnstandard: '0: Lace',
  },
  {
    crochet_gauge: '',
    id: 5,
    knit_gauge: '28',
    name: 'Fingering',
    ply: '4',
    wpi: '14',
    yarnstandard: '1: Super Fine',
  },
  {
    crochet_gauge: null,
    id: 10,
    knit_gauge: '24-26',
    name: 'Sport',
    ply: '5',
    wpi: '12',
    yarnstandard: '2: Fine',
  },
  {
    crochet_gauge: null,
    id: 11,
    knit_gauge: '22',
    name: 'DK',
    ply: '8',
    wpi: '11',
    yarnstandard: '3: Light',
  },
  {
    crochet_gauge: null,
    id: 12,
    knit_gauge: '20',
    name: 'Worsted',
    ply: '10',
    wpi: '9',
    yarnstandard: '4: Medium',
  },
  {
    crochet_gauge: '',
    id: 1,
    knit_gauge: '18',
    name: 'Aran',
    ply: '10',
    wpi: '8',
    yarnstandard: '4: Medium',
  },
  {
    crochet_gauge: '',
    id: 4,
    knit_gauge: '14-15',
    name: 'Bulky',
    ply: '12',
    wpi: '7',
    yarnstandard: '5: Bulky',
  },
  {
    crochet_gauge: '',
    id: 6,
    knit_gauge: '7-12',
    name: 'Super Bulky',
    ply: null,
    wpi: '5-6',
    yarnstandard: '6: Super Bulky',
  },
  {
    crochet_gauge: null,
    id: 16,
    knit_gauge: '0-6',
    name: 'Jumbo',
    ply: null,
    wpi: '0-4',
    yarnstandard: '7: Jumbo',
  },
];
